name: 📝 ドキュメント改善
description: ドキュメント（README/ガイド/APIリファレンスなど）の改善提案や不備報告
title: "[Docs]: "
labels: [documentation]
body:
  # TODO: uv + ruffを想定したpythonプロジェクトの例です。実際のプロジェクトに合わせて変更してください。
  - type: input
    id: summary
    attributes:
      label: 概要
      description: 改善したいドキュメント内容を簡潔に書いてください
      placeholder: "例: インストール手順のuv使用例を追記してほしい"
    validations:
      required: true

  - type: input
    id: doc_path
    attributes:
      label: 対象ファイル/URL
      description: 対象となるドキュメントのパスやURLを記載してください
      placeholder: "例: docs/getting-started.md（または該当セクションのURL）"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 現在の記述
      description: 現状の記載内容や問題点を引用・要約してください
      placeholder: |
        例:
        - Node.js 16 を前提としているが、実際は 18 以上が必要
        - コマンド例に古いオプションが含まれる
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案する修正内容
      description: 具体的な修正案や追記案、サンプルコードがあれば記載してください
      placeholder: |
        例:
        - 必要バージョンを "Node.js >= 18" に更新
        - uv と ruff を使ったセットアップ例を追加
    validations:
      required: true

  - type: textar
