name: ✨ 新機能リクエスト
description: 新しい機能の追加を提案するためのテンプレート
title: "[Feature]: "
labels: [feature_request]
body:
  - type: input
    id: summary
    attributes:
      label: 概要
      description: 提案する新機能の簡潔な説明を書いてください
      placeholder: "例: ユーザーがテーマを切り替えられる機能を追加してほしい"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 動機・背景
      description: なぜこの新機能が必要か、解決したい課題を書いてください
      placeholder: |
        例:
        - 夜間の利用時に画面が眩しいため、ダークモードが欲しい
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: 具体的な挙動・UI・技術的アプローチなどがあれば記載してください
      placeholder: "例: 設定画面にテーマ切り替えオプションを追加する"
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えた解決方法があれば書いてください
      placeholder: "例: OSのテーマ設定に自動追従する"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 補足情報
      description: 参考資料やスクリーンショット、関連Issue/PRなどがあれば記載してください
      placeholder: "例: 類似プロダクトのスクリーンショット、関連 #456"
    validations:
      required: false
