# ------------------------------------------------------------
# Workflow Name : Labeler
# Trigger       : pull_request_target (opened/synchronize/edited/reopened)
# Purpose       :
#   - 変更パス/ブランチ名に応じた自動ラベル付与
#   - 設定は .github/labeler.yml を使用
# ------------------------------------------------------------
name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml  # TODO: check .github/labeler.ymlを作成する必要はある？
